### PR TITLE
Add support for GHC 8.6, 8.4, and 8.2

### LINKED ISSUE #28: Support GHC 8.6?
I don't think Witch uses anything that actually requires GHC 8.8.

### PR DESCRIPTION
**Pull request by tfausak**
Fixes #28.

### CODE REVIEW

**Comment by tfausak** [comment]
@Mikolaj can you try out this branch with LambdaHack?

**Comment by Mikolaj** [comment]
Yes, with pleasure!

**Comment by Mikolaj** [comment]
Results are here: https://travis-ci.org/github/LambdaHack/LambdaHack

I think it failed due to test stanza in .cabal requiring too new packages.

**Comment by tfausak** [comment]
I think you're right: https://travis-ci.org/github/LambdaHack/LambdaHack/jobs/772529273#L1008

```
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: witch-0.3.2.0 (user goal)
[__1] rejecting: witch:!test (constraint from config file, command line flag, or user target requires opposite flag selection)
[__1] trying: witch:*test
[__2] trying: hspec-2.8.2 (dependency of witch *test)
[__3] trying: hspec-core-2.8.2 (dependency of hspec)
[__4] trying: setenv-0.1.1.3 (dependency of hspec-core)
[__5] next goal: unix (dependency of setenv)
[__5] rejecting: unix-2.7.2.2/installed-2.7.2.2 (conflict: witch => time>=1.9.1 && <1.12, unix => time==1.8.0.2/installed-1.8.0.2)
[__5] rejecting: unix-2.7.2.2, unix-2.7.2.1, unix-2.7.2.0, unix-2.7.1.0, unix-2.7.0.1, unix-2.7.0.0, unix-2.6.0.1, unix-2.6.0.0, unix-2.5.1.1, unix-2.5.1.0, unix-2.5.0.0, unix-2.4.2.0, unix-2.4.1.0, unix-2.4.0.2, unix-2.4.0.1, unix-2.4.0.0, unix-2.3.2.0, unix-2.3.1.0, unix-2.3.0.0, unix-2.2.0.0, unix-2.0 (constraint from project config TODO requires installed instance)
[__5] fail (backjumping, conflict set: setenv, unix, witch)
After searching the rest of the dependency tree exhaustively, these were the goals I've had most trouble fulfilling: witch, unix, setenv, hspec, hspec-core, witch:test
Try running with --minimize-conflict-set to improve the error message.
```

I'm not sure why your CI is trying to build Witch's test suite though. Perhaps because you're using Witch as a Git dependency, so it's picking up `tests: True` in the [`cabal.project`](https://github.com/tfausak/witch/blob/4f37a29b65f31d415b8b21565218fc8abe0ac585/cabal.project#L6) file?

I could probably remove that, but it might take some fiddling with my CI setup. Since it seems promising that this branch will work, I'll merge it and release a new version for you to test.

**Comment by tfausak** [comment]
Alright, you should be able to try with [witch-0.3.2.1](https://hackage.haskell.org/package/witch-0.3.2.1).

**Comment by Mikolaj** [comment]
Works great now, thank you: https://travis-ci.org/github/LambdaHack/LambdaHack/builds/772595973

If anybody asks, I will recommend your library for catching conversion bugs.

**Comment by tfausak** [comment]
Wonderful! Thanks for the endorsement :) 

For posterity, this commit did the switchover: https://github.com/LambdaHack/LambdaHack/commit/21d4fd17ecef18e0cc6552ef0c3a11d56545940b

**Pull request merged**
