### PR TITLE
Add aliases for encodings

### LINKED ISSUE #103: Add aliases for encodings
It's really tedious to do this:

``` hs
let string = "example" :: String
let byteString = via @(UTF_8 ByteString) string :: ByteString
```

Even just `via @(UTF_8 ByteString) "..."` (with everything else inferred) is pretty clunky. And it only gets worse if things are imported qualified. It would be nice to provide type aliases like this:

``` hs
type Utf8 = UTF_8 ByteString
-- similarly for other encodings
```

That way you could just say `via @Utf8 "..."` and be done with it. That's the main (only?) use case for the tagged encodings anyway. Might as well make it easy.

### PR DESCRIPTION
**Pull request by tfausak**
Fixes #103.

Still to do:

- Add documentation. Some basic usage examples would be nice. 
- Bike shed naming. How should lazy and strict be differentiated? What about little endian and big endian? 
- Consider deprecating `ISO_8859_1` in favor of `LATIN_1`, which is both shorter and what the `text` package calls it anyway.

### CODE REVIEW

**Comment by tfausak** [comment]
> How should lazy and strict be differentiated?

Options:

- As it is now, with `*Strict` and `*Lazy` suffixes.
- Make lazy variants have no suffix and strict variants have a `*'` suffix.
- Make strict variants have no suffix and lazy variants have `*Lazy` suffixes.
- As above, but with prefixes instead of suffixes. 
- As above, but with abbreviations (`S` & `L`) instead.

**Comment by tfausak** [comment]
> What about little endian and big endian?

Options:

- As it is now, with `*le` and `*be` suffixes.
- Same as above, but with uppercase suffixes instead. 
- Pick a default to have no suffix and only apply the suffix to the other one.
- Provide an option without the suffix that attempts to figure out the correct endianness. 

https://en.wikipedia.org/wiki/UTF-16#Byte-order_encoding_schemes

**Comment by tfausak** [comment]
It may be good to avoid using "strict" since it could mean either "not lazy" or "not lenient", both of which are applicable to encodings.

**Comment by tfausak** [comment]
Another alternative: Only provide aliases for strict byte strings. 

``` hs
type Utf8 = UTF_8 ByteString
via @Utf8 "..." :: ByteString
via @(UTF_8 LazyByteString) "..." :: LazyByteString
```

I have a hunch that conversions for strict byte strings are more common, but I don't know how to prove it. And if I later want to add aliases for lazy byte strings, I'll be right back here.

**Comment by goertzenator** [comment]
This is great!  About a year ago I tried to figure out text conversions but gave up in frustration.  Now it is very intuitive.

**Pull request merged**
