### PR TITLE
Update upper bounds for QuickCheck and bytestring

### PR DESCRIPTION
**Pull request by lehins**

### CODE REVIEW

**Review by tfausak — APPROVED** [review]
Thanks!

**Comment by lehins** [comment]
Absolutely. Can you also make a revision on Hackage? I am trying to get QuickCheck into nightly builds

**Comment by tfausak** [comment]
Will a new version work? I've already tagged [0.0.0.4](https://github.com/tfausak/witch/releases/tag/0.0.0.4). Once this build finishes it should be available on Hackage: https://github.com/tfausak/witch/actions/runs/402883596

**Comment by lehins** [comment]
Yeah, most definitely. Thank you!

**Pull request merged**
