### PR TITLE
composeTry, composeTryRhs and composeTryLhs combinators

### PR DESCRIPTION
**Pull request by 21it**
Hello! Thanks for awesome library and podcast! Here are some new features I found useful:

- Introduce `composeTry`, `composeTryRhs` and `composeTryLhs` combinators to allow deeper composition of `TryFrom.tryFrom` and `From.from` based expressions. 
- Couple of hspec tests for given combinators.
- Configs for various dev tools - ghcid, vim/coc, brittany, hie/haskell-language-server, nix.
- Nix and nix-shell support with option of running nix-shell inside docker container. Might be useful for people who are not using nix/nixos on host machine. 
- Small stack and cabal files adjustments.

### CODE REVIEW

**Comment by 21it** [comment]
Yes, `withSource` and `withTarget` make sense, as well as suggested combinators refactoring. That's easy, pushed corresponding commit. Question about `tryVia` vs `composeTry` is not that trivial. Actually `tryVia` is doing its job well, but obviously it allows to compose just `TryFrom` instances. In real code I do often need to compose `From` with `TryFrom` instances in left or right order, and as you mentioned it's not always that ergonomic. So my first thought was to just implement `tryViaLhs` and `tryViaRhs` to do that. But after some coding I did found that simpler combinators do look better for my taste - kinda similar features without loosing ergonomics. And they probably give more granular control as well, for example composition of two `TryFrom` and one `From` in between will look very simple (similar to examples in provided tests). Probably I'm a bit biased by my code style where I'm usually creating a ton of newtypes on top of each other, without exposing default constructors, using smart constructors instead (where it make sense) - so casual `coerce` of newtypes does not work that well in many cases, so composition of `From` and `TryFrom` instances might be handy to perform coerce of newtype to the given depth of newtype hierarchy. But I think it make sense to keep `via` and `tryVia` - they are useful as "shortcuts" which can be composed as well.

**Comment by tfausak** [comment]
I've opened #47 to add `withSource` and `withTarget`. 

I'm still thinking about this PR. Specifically:

- What's the smallest piece of useful functionality we can extract out of this? I don't want to add ghcid, Vim, HIE/HLS, and Nix configurations because I don't use them myself and they'll likely bit rot. Similarly if the `Ratio` instances are useful, those should go in a separate PR. 
- Is it possible to somehow combine `composeTry`, `composeTryRhs`, and `composeTryLhs`? It's a bit unfortunate that we need all three. The naming is inherently clunky.

**Comment by 21it** [comment]
Yeah, I completely understand an issue with unused tools, no problems at all. Feel free to extract any useful code from here and close this PR. Ratio instances are useful, I'm using them a lot, as well as composition combinators. Honestly I have no idea how to generalize them without additional types overhead. It's quite cool that at the moment it's possible to compose just functions without any wrappers. Names `composeTry`, `composeTryLhs` and `composeTryRhs` are quite long, but I think they are still better than custom cryptic infix combinators.

**Comment by tfausak** [comment]
Sorry about letting this sit around for so long! It's been on my mind, but I hadn't been able to decide how to move forward. I think I've figured out where I've landed though:

- The `withSource` and `withTarget` functions were added in #47 and released as part of version 1.0.0.0. They aren't exported from the top-level `Witch` module, but they're there if you want them. 
- I don't deal with `Ratio`s that much, so I'm not personally motivated to add their instances. But I'd be happy to review a separate PR for them. 
- As for `composeTry` and friends, I don't think I'll add them to Witch itself. I'd encourage you to publish a `witch-extras` library with combinators like that.

**Pull request closed without merging**
